server {
    listen 80;
    server_name _;

    # Endpoint zdrowia -> health-check-path: /health
    location /health {
        access_log off;
        add_header Content-Type application/json;
        return 200 '{"status":"UP"}';
    }

    # Strona glowna
    location / {
        add_header Content-Type text/plain;
        return 200 'hello from test-app';
    }
}
