name: 02 - Workflow Events

on: 
    push:
    pull_request:
    workflow_dispatch:
    schedule:
      - cron: '15 12 * * *' # Runs daily at midnight    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Triggered on ${{ github.event_name }}"
