name: 04 - Using Actions

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use an action to set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "19.x"

            - name: Install dependencies
              run: cd ./04-using-actions/react-app/react-app && npm ci

            - name: Run tests
              run: cd ./04-using-actions/react-app/react-app && npm run test
