name: 04 - Using Actions

on: push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Printing Folders
        run: echo "To jest struktura folderów:" && ls -la

    #  - name: Use an action to set up Node.js
    #    uses: actions/setup-node@v3
    #    with:
    #      node-version: '14'

    #  - name: Install dependencies
    #    run: npm install

    #  - name: Run tests
    #    run: npm test